name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      # - name: Install dependencies
      #   run: go mod tidy

      # - name: Build
      #   run: go build -v ./...

      # - name: Run Tests
      #   run: go test -v ./...
      
      - name: Final
        run: echo "🍏 Hello world! ${{ job.status }}."