name: Generate terraform docs

on:
  push:
    branches:
      - main
 
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
 
    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: docs/README.md
        output-method: replace
        git-push: "true"